### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pingfan-hu** [jhelvy/surveydown#17] opened 2024-05-23 23:58 UTC
I attempted to add the progress bar feature and had conversations with GPT.
### 1. `functions.R`
Following GPT's advice, I firstly modified the `sd_config()` in the functions.R file:
```{r}
sd_config <- function(
    ...,
    start_page = NULL,
    progress_bar = "top" // I added this.
) {
    ...,
    question_ids = unname(unlist(page_structure)),
    progress_bar = progress_bar // I added this.
  )
  ...
}
```
### 2. css file
Then, I created a `styles.css` file to store the progress bar layout:
```
#progress-container {
  display: none; /* Default to hidden */
  height: 5px;
  background-color: #f3f3f3;
}

#progress-bar {
  width: 0;
  height: 100%;
  background-color: #4caf50;
}
```
### 3. `js` file and `qmd` implementation
Finally, I created a `progress_bar.js` and included it in the YAML header in the `survey.qmd` file followed by an HTML division:
```
---
format: 
  html:
    section-divs: false
execute:
  echo: false
server: shiny
include-before-body: hide_pages.js
include-after-body: progress_bar.js // I added this.
theme: [cosmo, surveydown.scss]
css: styles.css // I added this.
---
// ... and this:
<div id="progress-container">
  <div id="progress-bar"></div>
</div>
```
I used `include-after-body` since the progress bar is having interactions with the page.
I cannot upload the `js` file but it can be accessed in our repo.

Now I've done everything but I still don't see the progress bar. I've had many trials with GPT but it doesn't have better solutions.

**Comment by jhelvy** [comment] 2024-06-11 13:16
I just checked the latest progress bar updates (#24) and first, amazing work! I notice a couple things though:

- The yaml option now doesn't work - if I change it from `"top"` to `"bottom"`, nothing changes (it's always at the top). Now that it looks like you're using JS to manage the bar, I wonder if you could change this from a yaml option and instead put it in the `sd_config()` function instead, like `progressbar = "top"` as an argument? In general I would prefer that as an option, but I don't know if it would work. If the implementation still requires the use of the `progressbar.lua` filter, then it will still have to be defined in the yaml. 
- Ideally the default progressbar color should be the primary color used in the theme. This should be do-able as I think you can specify the primary color using scss (not sure).
- The bar only updates correctly if you click on a question _in sequence_. If I skip to page 3 though and click on an answer, the bar should update to that position in the survey, but right now it just incrementally bumps up by one question. I think the expected behavior should be that the bar updates to the position of the latest answered question in the survey. For example, if there are 10 questions and the user skips to question 7 and answers it, the progress bar should update to 70%. This is because the user can't go backwards in the survey (at least for now), so if they're on question 7, then they are indeed 70% to the end of the survey (there would only be 3 questions left from that position).

**Comment by pingfan-hu** [comment] 2024-06-15 08:32
Please try with the new version of my updates. I didn't attempt to dynamically match the primary color, since the progressbar is defined in the lua file, but I left 4 color options for the bar and set green as default.

**Comment by jhelvy** [comment] 2024-06-22 19:43
I'm closing this because I think this has mostly been solved.

**Closed by jhelvy** 2024-06-22 19:43 UTC
